# url: "" # the base hostname & protocol for your site, e.g. http://example.com
# baseurl: "" # the subpath of your site, e.g. /blog
title: "Huiping Ren" 
description: "Ph.D. in Accounting at USC Marshall"
lang: en
# theme: academic-jekyll-theme
# $ gem install academic-jekyll-theme


# layout
show_social: true
show_excerpts: false
show_frame: true
show_sidebar: false


# Menu

Navigation:
- {title: "About Me", file: "home.md"}
- {title: "CV", file: "cv.md"}
- {title: "Personal", file: "personal.md"}
- {title: "Contact", file: "contact.md"}
